# Generated by Django 5.0.2 on 2024-03-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=15)),
                ('tipo_cargo', models.SmallIntegerField()),
                ('estado_cargo', models.SmallIntegerField()),
                ('fecha_creacion_cargo', models.DateTimeField()),
                ('fecha_modificacion_cargo', models.DateTimeField()),
            ],
            options={
                'db_table': 'cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=15)),
                ('estado_rol', models.SmallIntegerField()),
                ('fecha_creacion_rol', models.DateTimeField()),
                ('fecha_modificacion_rol', models.DateTimeField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('numero_unidad', models.IntegerField()),
                ('nombre_unidad', models.CharField(max_length=50)),
                ('estado_unidad', models.SmallIntegerField()),
                ('fecha_creacion_unidad', models.DateTimeField()),
                ('fecha_modificacion_unidad', models.DateTimeField()),
            ],
            options={
                'db_table': 'unidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_usuario', models.CharField(max_length=100)),
                ('contraseña_usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
