# Generated by Django 5.0.2 on 2024-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_rename_nombre_cargos_nombre_cargo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargos',
            old_name='nombre_cargo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='nombre_rol',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='unidades',
            old_name='nombre_unidad',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_usuario',
            field=models.EmailField(max_length=254),
        ),
    ]
