# Generated by Django 5.0.2 on 2024-03-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_nombre_cargo_cargos_nombre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargos',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Unidades',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
