# Generated by Django 5.0.2 on 2024-04-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_cargos_roles_unidades_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
