# Generated by Django 5.0.2 on 2024-04-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_cargo_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimientos', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimientos', models.CharField(max_length=100)),
                ('fecha_creacion_movimientos', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_movimientos', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
    ]
