# Generated by Django 5.0.3 on 2024-07-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_movimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id_coneion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_base_conexion', models.CharField(max_length=100)),
                ('usuario_conexion', models.CharField(max_length=100)),
                ('contraseña_conexion', models.CharField(blank=True, max_length=100, null=True)),
                ('host_conexion', models.CharField(max_length=100)),
                ('puerto_conexion', models.IntegerField()),
                ('gestor_conexion', models.CharField(default='PostgreSQL', max_length=100)),
            ],
            options={
                'db_table': 'conexiones',
                'managed': False,
            },
        ),
    ]
