# Generated by Django 5.0.3 on 2024-07-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_mysqlconnection_delete_conexion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mysqlconnection',
            table='mysql',
        ),
    ]
