# Generated by Django 5.0.3 on 2024-07-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_mongodbconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqLiteConnection',
            fields=[
                ('id_conexion', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_conexion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sqlite',
            },
        ),
    ]
